import type { Meal, Ingredient, Recipe, Category, User, Report, MealPlanEntry } from "./types";

const IMG = (id: string, w = 800, h = 600) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format`;

export const CATEGORIES: Category[] = [
  { id: "breakfast", name: "Breakfast", description: "Start your day right with these energizing morning meals.", image: IMG("1664993101841-036f189719b6"), mealCount: 6, color: "#F59E0B" },
  { id: "lunch", name: "Lunch", description: "Satisfying midday meals to keep you going.", image: IMG("1665332195309-9d75071138f0"), mealCount: 8, color: "#10B981" },
  { id: "dinner", name: "Dinner", description: "Hearty evening meals for the whole family.", image: IMG("1763048443535-1243379234e2"), mealCount: 10, color: "#6366F1" },
  { id: "soups", name: "Soups", description: "Rich and flavorful soups from the Akwa Ibom tradition.", image: IMG("1667515349748-17ea9ee9a252"), mealCount: 8, color: "#EF4444" },
  { id: "rice", name: "Rice Dishes", description: "Classic Nigerian rice preparations loved across the country.", image: IMG("1665556899022-9761f95769e5"), mealCount: 5, color: "#F97316" },
  { id: "swallow", name: "Swallow", description: "Traditional starchy foods eaten with Nigerian soups.", image: IMG("1664992960082-0ea299a9c53e"), mealCount: 4, color: "#8B5CF6" },
  { id: "local", name: "Local Meals", description: "Authentic traditional meals from Ikot Ekpene and Akwa Ibom.", image: IMG("1673465580365-b96bef916770"), mealCount: 12, color: "#E06000" },
  { id: "snacks", name: "Snacks", description: "Light bites and popular Nigerian street snacks.", image: IMG("1647162264554-5f60af27f052"), mealCount: 5, color: "#EC4899" },
  { id: "drinks", name: "Drinks", description: "Refreshing traditional Nigerian beverages.", image: IMG("1664993090321-b2caff794431"), mealCount: 3, color: "#06B6D4" },
  { id: "protein", name: "Protein", description: "Meat, fish and poultry preparations.", image: IMG("1650815232474-12d5b9375d63"), mealCount: 4, color: "#84CC16" },
  { id: "vegetables", name: "Vegetables", description: "Nutritious vegetable-based dishes.", image: IMG("1667515349366-457d8a750fe1"), mealCount: 3, color: "#22C55E" },
  { id: "desserts", name: "Desserts", description: "Sweet treats and after-meal delights.", image: IMG("1563336522-c3bd728d3b45"), mealCount: 3, color: "#F43F5E" },
];

export const MEALS: Meal[] = [
  { id: "afang-soup", name: "Afang Soup", description: "Afang Soup is a rich, nutritious vegetable soup native to the Efik and Ibibio people of Akwa Ibom and Cross River states. It is prepared with Afang leaves (wild spinach), waterleaf, assorted proteins and palm oil. This soup is a staple in Ikot Ekpene homes.", category: "soups", mealType: "Dinner", image: IMG("1667515349748-17ea9ee9a252"), prepTime: 20, cookTime: 35, servings: 4, difficulty: "Medium", status: "published", featured: true, createdAt: "2024-01-10", tags: ["local", "vegetable", "traditional"] },
  { id: "edikang-ikong", name: "Edikang Ikong", description: "Edikang Ikong is a highly nutritious Nigerian soup made with ugu (pumpkin leaves) and waterleaf. It is considered one of the most popular soups from the Efik people and is rich in protein, vitamins and minerals.", category: "soups", mealType: "Dinner", image: IMG("1673465580365-b96bef916770"), prepTime: 25, cookTime: 40, servings: 4, difficulty: "Medium", status: "published", featured: true, createdAt: "2024-01-11", tags: ["local", "vegetable", "traditional"] },
  { id: "jollof-rice", name: "Jollof Rice", description: "Jollof Rice is the most iconic West African dish — perfectly seasoned long-grain rice cooked in a rich tomato and pepper base. Nigerian jollof, also called party jollof, is beloved for its smoky flavor and vibrant colour.", category: "rice", mealType: "Lunch", image: IMG("1665332195309-9d75071138f0"), prepTime: 15, cookTime: 45, servings: 6, difficulty: "Easy", status: "published", featured: true, createdAt: "2024-01-12", tags: ["popular", "rice", "party"] },
  { id: "egusi-soup", name: "Egusi Soup", description: "Egusi Soup is a thick, hearty Nigerian soup made from ground melon seeds cooked with leafy greens, palm oil and assorted proteins. It is eaten across all parts of Nigeria and is particularly popular in Akwa Ibom.", category: "soups", mealType: "Dinner", image: IMG("1763048443535-1243379234e2"), prepTime: 20, cookTime: 40, servings: 4, difficulty: "Easy", status: "published", featured: true, createdAt: "2024-01-13", tags: ["popular", "soup", "traditional"] },
  { id: "fried-rice", name: "Fried Rice", description: "Nigerian Fried Rice is a colorful, flavorful rice dish cooked with mixed vegetables, liver, and perfectly seasoned. Unlike Chinese fried rice, the Nigerian version has a distinct and unforgettable taste.", category: "rice", mealType: "Lunch", image: IMG("1665556899022-9761f95769e5"), prepTime: 20, cookTime: 30, servings: 6, difficulty: "Medium", status: "published", featured: true, createdAt: "2024-01-14", tags: ["popular", "rice"] },
  { id: "pounded-yam", name: "Pounded Yam", description: "Pounded Yam is a smooth, stretchy swallow made from boiled and pounded yam. It is the perfect companion to any Nigerian soup and is a staple across southern Nigeria, especially in Akwa Ibom.", category: "swallow", mealType: "Dinner", image: IMG("1664992960082-0ea299a9c53e"), prepTime: 10, cookTime: 25, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-15", tags: ["swallow", "traditional"] },
  { id: "ekpang-nkukwo", name: "Ekpang Nkukwo", description: "Ekpang Nkukwo is a traditional Efik delicacy from Akwa Ibom, made with grated cocoyam wrapped around various proteins, crayfish and palm oil. It is a special meal often prepared for ceremonies and celebrations.", category: "local", mealType: "Dinner", image: IMG("1764314108477-f026172e32a9"), prepTime: 45, cookTime: 60, servings: 6, difficulty: "Hard", status: "published", featured: true, createdAt: "2024-01-16", tags: ["local", "traditional", "special"] },
  { id: "pepper-soup", name: "Pepper Soup", description: "Nigerian Pepper Soup is a light, spicy broth made with assorted meat or fish, traditional pepper soup spices and local herbs. It is warming, aromatic and often served as a starter or remedy for cold and fatigue.", category: "soups", mealType: "Any", image: IMG("1764314108477-f026172e32a9"), prepTime: 10, cookTime: 30, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-17", tags: ["soup", "spicy"] },
  { id: "akara", name: "Akara", description: "Akara are crispy Nigerian bean cakes made from peeled black-eyed peas blended with peppers and onions, then deep-fried to golden perfection. They are a beloved breakfast staple across Nigeria.", category: "breakfast", mealType: "Breakfast", image: IMG("1647162264554-5f60af27f052"), prepTime: 20, cookTime: 15, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-18", tags: ["breakfast", "beans", "fried"] },
  { id: "moi-moi", name: "Moi Moi", description: "Moi Moi is a steamed Nigerian bean pudding made from ground black-eyed peas, peppers and various seasonings. It can include boiled eggs, fish or crayfish inside for extra flavor and protein.", category: "breakfast", mealType: "Breakfast", image: IMG("1664993101841-036f189719b6"), prepTime: 30, cookTime: 40, servings: 6, difficulty: "Medium", status: "published", featured: false, createdAt: "2024-01-19", tags: ["breakfast", "beans", "steamed"] },
  { id: "okro-soup", name: "Okro Soup", description: "Okro Soup (Okra Soup) is a slimy, nutritious Nigerian soup made with fresh okra, assorted proteins, crayfish and palm oil. It can be prepared with or without tomatoes and is typically eaten with any swallow.", category: "soups", mealType: "Dinner", image: IMG("1637668895982-893b7df2a59a"), prepTime: 15, cookTime: 30, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-20", tags: ["soup", "vegetable"] },
  { id: "atama-soup", name: "Atama Soup", description: "Atama Soup is a traditional Efik soup from Akwa Ibom made with atama leaves, palm nut extract, crayfish and assorted protein. It has a distinctive rich, earthy flavor and deep orange color from the palm nuts.", category: "soups", mealType: "Dinner", image: IMG("1667515349366-457d8a750fe1"), prepTime: 30, cookTime: 50, servings: 4, difficulty: "Hard", status: "published", featured: false, createdAt: "2024-01-21", tags: ["local", "traditional", "soup"] },
  { id: "editan-soup", name: "Editan Soup", description: "Editan Soup is made with editan leaves (Lasianthera africana), a slightly bitter leaf native to Akwa Ibom. When prepared with palm oil, crayfish and protein, the bitterness mellows into a rich, complex flavor.", category: "soups", mealType: "Dinner", image: IMG("1782174176872-50564933cb45"), prepTime: 20, cookTime: 35, servings: 4, difficulty: "Medium", status: "published", featured: false, createdAt: "2024-01-22", tags: ["local", "traditional", "soup"] },
  { id: "coconut-rice", name: "Coconut Rice", description: "Coconut Rice is a fragrant, slightly sweet Nigerian rice dish cooked in coconut milk with spices and vegetables. It pairs wonderfully with fried fish or chicken and is especially popular in coastal regions.", category: "rice", mealType: "Lunch", image: IMG("1739217744880-472f59559cc5"), prepTime: 10, cookTime: 30, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-23", tags: ["rice", "coconut"] },
  { id: "native-rice", name: "Native Rice (Ofada)", description: "Native Rice, also called Ofada Rice, is a local unpolished Nigerian rice variety with a distinct earthy aroma. It is traditionally served with spicy Ayamase (ofada) stew.", category: "rice", mealType: "Lunch", image: IMG("1665332305771-e49a5dd5ba80"), prepTime: 15, cookTime: 40, servings: 4, difficulty: "Medium", status: "published", featured: false, createdAt: "2024-01-24", tags: ["rice", "local", "traditional"] },
  { id: "fufu", name: "Fufu", description: "Fufu is a smooth, stretchy swallow made from fermented cassava. It has a slightly sour taste and dense texture, and is traditionally eaten by rolling into small balls and dipping into Nigerian soups.", category: "swallow", mealType: "Dinner", image: IMG("1664993085274-80c6ba725ccc"), prepTime: 5, cookTime: 20, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-25", tags: ["swallow", "cassava", "traditional"] },
  { id: "garri-eba", name: "Garri (Eba)", description: "Eba is made by adding garri (dried cassava flakes) to boiling water and stirring vigorously until a firm, smooth dough forms. It is one of the most affordable and widely eaten swallows in Nigeria.", category: "swallow", mealType: "Dinner", image: IMG("1664993090321-b2caff794431"), prepTime: 5, cookTime: 10, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-26", tags: ["swallow", "cassava"] },
  { id: "suya", name: "Suya", description: "Suya is a spiced Nigerian grilled meat skewer, marinated in suya spice (yaji), ginger and other seasonings. It is a popular street food enjoyed across Nigeria, often served with sliced onions and tomatoes.", category: "protein", mealType: "Any", image: IMG("1650815232474-12d5b9375d63"), prepTime: 60, cookTime: 20, servings: 4, difficulty: "Medium", status: "published", featured: false, createdAt: "2024-01-27", tags: ["grilled", "protein", "street food"] },
  { id: "grilled-chicken", name: "Grilled Chicken", description: "Nigerian-style Grilled Chicken is marinated in a blend of local spices, suya pepper, ginger, garlic and seasoning cubes, then grilled over charcoal or in the oven until perfectly charred and juicy.", category: "protein", mealType: "Any", image: IMG("1650815232474-12d5b9375d63"), prepTime: 120, cookTime: 45, servings: 4, difficulty: "Medium", status: "published", featured: false, createdAt: "2024-01-28", tags: ["grilled", "chicken", "protein"] },
  { id: "pap-akamu", name: "Pap (Akamu)", description: "Pap, also known as Akamu or Ogi, is a smooth, warm Nigerian fermented corn porridge. It is commonly served at breakfast with Akara or Moi Moi and is a staple weaning food for children.", category: "breakfast", mealType: "Breakfast", image: IMG("1664993090321-b2caff794431"), prepTime: 5, cookTime: 10, servings: 2, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-29", tags: ["breakfast", "corn", "porridge"] },
  { id: "plantain-dodo", name: "Fried Plantain (Dodo)", description: "Dodo is sweet, caramelized fried plantain — a beloved Nigerian side dish and snack. The ripe plantain is sliced and fried until golden and soft inside. It pairs with virtually any Nigerian meal.", category: "snacks", mealType: "Any", image: IMG("1563336522-c3bd728d3b45"), prepTime: 5, cookTime: 10, servings: 2, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-01-30", tags: ["plantain", "fried", "snack"] },
  { id: "puff-puff", name: "Puff Puff", description: "Puff Puff is a popular Nigerian fried dough snack similar to doughnuts. Made from a simple batter of flour, yeast, sugar and nutmeg, then deep-fried to golden puffiness. A beloved party and street food.", category: "snacks", mealType: "Snack", image: IMG("1647162264554-5f60af27f052"), prepTime: 30, cookTime: 15, servings: 8, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-01", tags: ["snack", "fried", "dough"] },
  { id: "zobo", name: "Zobo Drink", description: "Zobo is a refreshing Nigerian drink made from dried hibiscus flowers (Roselle) boiled with ginger, cloves and pineapple. It has a beautiful deep ruby color and tangy-sweet flavor. Served chilled.", category: "drinks", mealType: "Any", image: IMG("1664993085274-80c6ba725ccc"), prepTime: 10, cookTime: 20, servings: 6, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-02", tags: ["drink", "hibiscus", "refreshing"] },
  { id: "kunu", name: "Kunu Drink", description: "Kunu is a traditional Nigerian non-alcoholic drink made from millet, sorghum or rice blended with ginger, cloves and other spices. It is slightly sweet, milky and very nutritious.", category: "drinks", mealType: "Any", image: IMG("1664993090321-b2caff794431"), prepTime: 60, cookTime: 0, servings: 6, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-03", tags: ["drink", "millet", "traditional"] },
  { id: "banga-soup", name: "Banga Soup", description: "Banga Soup (Ofe Akwu) is a rich, orange palm nut soup cooked with dried fish, crayfish, Banga spice and assorted proteins. It is native to the Niger Delta and is one of the most aromatic Nigerian soups.", category: "soups", mealType: "Dinner", image: IMG("1637668895982-893b7df2a59a"), prepTime: 30, cookTime: 50, servings: 4, difficulty: "Medium", status: "published", featured: false, createdAt: "2024-02-04", tags: ["soup", "palm nut", "local"] },
  { id: "bread-egg", name: "Bread & Fried Egg", description: "A classic Nigerian breakfast — thick slices of soft white bread served with a perfectly fried egg seasoned with pepper and onion. Simple, filling and ready in under 10 minutes.", category: "breakfast", mealType: "Breakfast", image: IMG("1664993101841-036f189719b6"), prepTime: 5, cookTime: 8, servings: 1, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-05", tags: ["breakfast", "bread", "egg", "quick"] },
  { id: "white-rice-stew", name: "White Rice & Tomato Stew", description: "Plain boiled white rice served with a rich, spiced Nigerian tomato and pepper stew with chicken or beef. A simple, everyday meal eaten by millions of Nigerians for lunch.", category: "rice", mealType: "Lunch", image: IMG("1665332305771-e49a5dd5ba80"), prepTime: 10, cookTime: 35, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-06", tags: ["rice", "stew", "everyday"] },
  { id: "semolina", name: "Semolina", description: "Semolina is a smooth, stretchy swallow made from durum wheat semolina. It has a lighter texture compared to pounded yam and is a popular alternative swallow across Nigeria.", category: "swallow", mealType: "Dinner", image: IMG("1664992960082-0ea299a9c53e"), prepTime: 5, cookTime: 15, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-07", tags: ["swallow", "wheat"] },
  { id: "fish-pepper-soup", name: "Fish Pepper Soup", description: "Fish Pepper Soup is a light but intensely flavored Nigerian broth made with fresh fish, traditional pepper soup spices, utazi leaves and other herbs. It is aromatic, warming and deeply satisfying.", category: "soups", mealType: "Lunch", image: IMG("1782174176872-50564933cb45"), prepTime: 10, cookTime: 25, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-08", tags: ["soup", "fish", "spicy"] },
  { id: "vegetable-stir-fry", name: "Nigerian Vegetable Stir-fry", description: "A quick and nutritious stir-fry of local Nigerian vegetables — ugu leaves, carrots, bell peppers and onions — cooked in a small amount of oil with garlic and seasoning. Light, healthy and colorful.", category: "vegetables", mealType: "Lunch", image: IMG("1667515349366-457d8a750fe1"), prepTime: 10, cookTime: 10, servings: 2, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-09", tags: ["vegetable", "healthy", "quick"] },
  { id: "chin-chin", name: "Chin Chin", description: "Chin Chin is a crunchy, deep-fried Nigerian snack made from a simple dough of flour, sugar, butter and milk, seasoned with nutmeg. It is a favourite at parties, celebrations and as a daily snack.", category: "snacks", mealType: "Snack", image: IMG("1664993090321-b2caff794431"), prepTime: 30, cookTime: 20, servings: 10, difficulty: "Medium", status: "published", featured: false, createdAt: "2024-02-10", tags: ["snack", "fried", "crunchy"] },
  { id: "pancakes", name: "Nigerian Pancakes", description: "Nigerian Pancakes are thin, slightly sweet crepes made from a smooth batter of flour, eggs, milk and a touch of vanilla. They are rolled or folded and enjoyed at breakfast with honey or jam.", category: "breakfast", mealType: "Breakfast", image: IMG("1664993101841-036f189719b6"), prepTime: 10, cookTime: 15, servings: 4, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-11", tags: ["breakfast", "sweet"] },
  { id: "tea-bread", name: "Tea & Bread", description: "Hot Lipton tea served with sliced white or agege bread, sometimes with butter and oleo margarine spread. A simple, comforting Nigerian morning ritual enjoyed across all age groups.", category: "breakfast", mealType: "Breakfast", image: IMG("1664993101841-036f189719b6"), prepTime: 5, cookTime: 5, servings: 1, difficulty: "Easy", status: "published", featured: false, createdAt: "2024-02-12", tags: ["breakfast", "tea", "quick"] },
];

export const INGREDIENTS: Ingredient[] = [
  { id: "afang-leaves", name: "Afang Leaves", description: "Wild spinach native to Akwa Ibom", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 1 },
  { id: "waterleaf", name: "Waterleaf", description: "Succulent leafy vegetable", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 3 },
  { id: "ugu-leaves", name: "Ugu Leaves (Pumpkin Leaves)", description: "Fluted pumpkin leaves", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 2 },
  { id: "beef", name: "Beef", description: "Fresh beef cuts", category: "Protein", unit: "g", status: "active", mealsUsedIn: 8 },
  { id: "goat-meat", name: "Goat Meat", description: "Fresh goat meat cuts", category: "Protein", unit: "g", status: "active", mealsUsedIn: 5 },
  { id: "chicken", name: "Chicken", description: "Whole or cut chicken pieces", category: "Protein", unit: "g", status: "active", mealsUsedIn: 6 },
  { id: "stockfish", name: "Stockfish", description: "Dried and salted cod", category: "Protein", unit: "g", status: "active", mealsUsedIn: 6 },
  { id: "dried-fish", name: "Dried Fish (Panla)", description: "Smoked/dried fish for flavoring", category: "Protein", unit: "g", status: "active", mealsUsedIn: 7 },
  { id: "fresh-fish", name: "Fresh Catfish", description: "Fresh river catfish", category: "Protein", unit: "g", status: "active", mealsUsedIn: 3 },
  { id: "palm-oil", name: "Palm Oil", description: "Red/unrefined palm oil", category: "Oil & Fat", unit: "ml", status: "active", mealsUsedIn: 12 },
  { id: "crayfish", name: "Crayfish (Ground)", description: "Ground dried crayfish for soup base", category: "Seasoning", unit: "g", status: "active", mealsUsedIn: 15 },
  { id: "pepper", name: "Scotch Bonnet Pepper", description: "Fresh hot peppers", category: "Spice", unit: "g", status: "active", mealsUsedIn: 18 },
  { id: "onion", name: "Onion", description: "Medium-sized onions", category: "Vegetables", unit: "pieces", status: "active", mealsUsedIn: 20 },
  { id: "seasoning-cubes", name: "Seasoning Cubes (Maggi/Knorr)", description: "Stock cubes for flavoring", category: "Seasoning", unit: "cubes", status: "active", mealsUsedIn: 25 },
  { id: "salt", name: "Salt", description: "Table salt", category: "Seasoning", unit: "to taste", status: "active", mealsUsedIn: 30 },
  { id: "long-grain-rice", name: "Long Grain Rice", description: "Parboiled long grain rice", category: "Grains", unit: "cups", status: "active", mealsUsedIn: 4 },
  { id: "tomatoes", name: "Tomatoes", description: "Fresh ripe tomatoes", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 12 },
  { id: "tomato-paste", name: "Tomato Paste", description: "Concentrated tomato paste", category: "Condiment", unit: "tablespoons", status: "active", mealsUsedIn: 6 },
  { id: "vegetable-oil", name: "Vegetable Oil", description: "Refined vegetable cooking oil", category: "Oil & Fat", unit: "ml", status: "active", mealsUsedIn: 10 },
  { id: "yam", name: "Yam", description: "White yam for pounding", category: "Tubers", unit: "kg", status: "active", mealsUsedIn: 2 },
  { id: "egusi", name: "Egusi (Melon Seeds)", description: "Ground melon/egusi seeds", category: "Seeds", unit: "g", status: "active", mealsUsedIn: 1 },
  { id: "cocoyam", name: "Cocoyam", description: "Fresh cocoyam/taro root", category: "Tubers", unit: "g", status: "active", mealsUsedIn: 1 },
  { id: "black-eyed-peas", name: "Black-eyed Peas (Beans)", description: "Dried black-eyed beans", category: "Legumes", unit: "g", status: "active", mealsUsedIn: 2 },
  { id: "mixed-vegetables", name: "Mixed Vegetables", description: "Carrots, green beans, corn mix", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 2 },
  { id: "ginger", name: "Fresh Ginger", description: "Fresh ginger root", category: "Spice", unit: "g", status: "active", mealsUsedIn: 8 },
  { id: "garlic", name: "Garlic", description: "Fresh garlic cloves", category: "Spice", unit: "cloves", status: "active", mealsUsedIn: 7 },
  { id: "bay-leaf", name: "Bay Leaf", description: "Dried bay leaves", category: "Herbs", unit: "pieces", status: "active", mealsUsedIn: 4 },
  { id: "suya-spice", name: "Suya Spice (Yaji)", description: "Ground suya pepper mix", category: "Spice", unit: "tablespoons", status: "active", mealsUsedIn: 2 },
  { id: "okra", name: "Fresh Okra", description: "Fresh okra/lady fingers", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 1 },
  { id: "plantain", name: "Ripe Plantain", description: "Ripe sweet plantains", category: "Fruits", unit: "pieces", status: "active", mealsUsedIn: 1 },
  { id: "flour", name: "Plain Flour", description: "All-purpose wheat flour", category: "Grains", unit: "g", status: "active", mealsUsedIn: 3 },
  { id: "eggs", name: "Eggs", description: "Fresh hen eggs", category: "Protein", unit: "pieces", status: "active", mealsUsedIn: 5 },
  { id: "coconut-milk", name: "Coconut Milk", description: "Thick coconut milk", category: "Dairy/Alternative", unit: "ml", status: "active", mealsUsedIn: 1 },
  { id: "hibiscus", name: "Dried Hibiscus (Zobo)", description: "Dried roselle flowers", category: "Herbs", unit: "g", status: "active", mealsUsedIn: 1 },
  { id: "yeast", name: "Instant Dry Yeast", description: "For bread and puff puff", category: "Baking", unit: "g", status: "active", mealsUsedIn: 2 },
  { id: "atama-leaves", name: "Atama Leaves", description: "Traditional Efik soup leaves", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 1 },
  { id: "editan-leaves", name: "Editan Leaves", description: "Lasianthera africana leaves", category: "Vegetables", unit: "g", status: "active", mealsUsedIn: 1 },
  { id: "palm-nut", name: "Palm Nut Concentrate", description: "Extracted palm nut juice", category: "Oil & Fat", unit: "ml", status: "active", mealsUsedIn: 2 },
  { id: "liver", name: "Beef Liver", description: "Fresh beef liver", category: "Protein", unit: "g", status: "active", mealsUsedIn: 2 },
  { id: "mixed-spices", name: "Mixed Pepper Soup Spice", description: "Traditional pepper soup spice blend", category: "Spice", unit: "tablespoons", status: "active", mealsUsedIn: 3 },
];

export const RECIPES: Recipe[] = [
  {
    id: "recipe-afang",
    mealId: "afang-soup",
    ingredients: [
      { ingredientId: "afang-leaves", ingredientName: "Afang Leaves", quantity: 200, unit: "g" },
      { ingredientId: "waterleaf", ingredientName: "Waterleaf", quantity: 300, unit: "g" },
      { ingredientId: "beef", ingredientName: "Beef", quantity: 500, unit: "g" },
      { ingredientId: "stockfish", ingredientName: "Stockfish", quantity: 100, unit: "g" },
      { ingredientId: "dried-fish", ingredientName: "Dried Fish", quantity: 80, unit: "g" },
      { ingredientId: "palm-oil", ingredientName: "Palm Oil", quantity: 150, unit: "ml" },
      { ingredientId: "crayfish", ingredientName: "Ground Crayfish", quantity: 50, unit: "g" },
      { ingredientId: "pepper", ingredientName: "Scotch Bonnet Pepper", quantity: 4, unit: "pieces" },
      { ingredientId: "onion", ingredientName: "Onion", quantity: 1, unit: "piece" },
      { ingredientId: "seasoning-cubes", ingredientName: "Seasoning Cubes", quantity: 2, unit: "cubes" },
      { ingredientId: "salt", ingredientName: "Salt", quantity: "to taste", unit: "" },
    ],
    preparationSteps: [
      "Wash the Afang leaves thoroughly in cold water. Slice into thin shreds.",
      "Wash and roughly chop the waterleaf. Squeeze out excess water.",
      "Soak stockfish in warm water for 30 minutes to soften. Wash and debone.",
      "Wash the beef and cut into bite-sized pieces. Season with salt, onion and seasoning cubes.",
      "Blend or pound the pepper and set aside.",
    ],
    cookingSteps: [
      { id: "cs-a1", mealId: "afang-soup", stepNumber: 1, title: "Cook the Meat", instruction: "Place the seasoned beef and stockfish in a pot. Add water, onion and one seasoning cube. Cook over medium heat for 20–25 minutes until the meat is tender. Add the dried fish in the last 5 minutes.", duration: 25 },
      { id: "cs-a2", mealId: "afang-soup", stepNumber: 2, title: "Add Palm Oil & Crayfish", instruction: "Add the palm oil, ground crayfish and blended pepper to the pot. Stir well and cook on medium heat for 8–10 minutes, allowing the oil to fry the crayfish base.", duration: 10 },
      { id: "cs-a3", mealId: "afang-soup", stepNumber: 3, title: "Add the Waterleaf", instruction: "Add the chopped waterleaf to the pot. Stir and cook for 3–4 minutes. The waterleaf will release moisture, helping to form the soup base.", duration: 4 },
      { id: "cs-a4", mealId: "afang-soup", stepNumber: 4, title: "Add the Afang Leaves", instruction: "Add the shredded Afang leaves. Stir gently to combine all ingredients. Do not overcook — Afang leaves should remain slightly firm for texture and nutrition.", duration: 3 },
      { id: "cs-a5", mealId: "afang-soup", stepNumber: 5, title: "Adjust Seasoning & Serve", instruction: "Taste and adjust salt and seasoning cubes as needed. Cook for 2 more minutes, then remove from heat. Serve hot with Pounded Yam, Fufu or Eba.", duration: 3 },
    ],
  },
  {
    id: "recipe-jollof",
    mealId: "jollof-rice",
    ingredients: [
      { ingredientId: "long-grain-rice", ingredientName: "Long Grain Rice", quantity: 3, unit: "cups" },
      { ingredientId: "tomatoes", ingredientName: "Fresh Tomatoes", quantity: 400, unit: "g" },
      { ingredientId: "pepper", ingredientName: "Scotch Bonnet Pepper", quantity: 3, unit: "pieces" },
      { ingredientId: "onion", ingredientName: "Onion", quantity: 2, unit: "pieces" },
      { ingredientId: "tomato-paste", ingredientName: "Tomato Paste", quantity: 3, unit: "tablespoons" },
      { ingredientId: "vegetable-oil", ingredientName: "Vegetable Oil", quantity: 100, unit: "ml" },
      { ingredientId: "chicken", ingredientName: "Chicken (optional)", quantity: 500, unit: "g" },
      { ingredientId: "seasoning-cubes", ingredientName: "Seasoning Cubes", quantity: 3, unit: "cubes" },
      { ingredientId: "bay-leaf", ingredientName: "Bay Leaves", quantity: 2, unit: "pieces" },
      { ingredientId: "salt", ingredientName: "Salt", quantity: "to taste", unit: "" },
    ],
    preparationSteps: [
      "Wash the rice thoroughly in cold water until the water runs clear. Parboil for 10 minutes, drain and set aside.",
      "Blend the tomatoes, scotch bonnet pepper and one onion together into a smooth purée.",
      "Season and cook the chicken with half onion, seasoning cube and salt until tender. Reserve the chicken stock.",
    ],
    cookingSteps: [
      { id: "cs-j1", mealId: "jollof-rice", stepNumber: 1, title: "Fry the Tomato Purée", instruction: "Heat oil in a large pot over medium-high heat. Add the remaining sliced onion and fry for 2 minutes. Add the tomato paste and stir-fry for 3 minutes. Add the blended tomato-pepper mixture and cook for 15–20 minutes, stirring frequently, until the tomato is fried and oil floats to the top.", duration: 22 },
      { id: "cs-j2", mealId: "jollof-rice", stepNumber: 2, title: "Add Stock & Season", instruction: "Add the reserved chicken stock (or water), seasoning cubes, bay leaves, salt and stir. Taste and adjust seasoning — the liquid should taste slightly saltier than preferred as the rice will absorb it.", duration: 5 },
      { id: "cs-j3", mealId: "jollof-rice", stepNumber: 3, title: "Cook the Rice", instruction: "Add the parboiled rice to the pot and stir to coat in the tomato base. The liquid should just cover the rice. Cover tightly and cook on medium heat for 15 minutes.", duration: 15 },
      { id: "cs-j4", mealId: "jollof-rice", stepNumber: 4, title: "Reduce Heat & Steam", instruction: "Reduce the heat to very low. Stir the rice from the bottom to prevent burning. Cover again and cook for another 10 minutes on very low heat until rice is fully cooked and has a slight smoky 'party' aroma.", duration: 10 },
      { id: "cs-j5", mealId: "jollof-rice", stepNumber: 5, title: "Rest & Serve", instruction: "Remove from heat and let the rice rest covered for 5 minutes. Fluff with a fork and serve with fried chicken, coleslaw or plantain.", duration: 5 },
    ],
  },
  {
    id: "recipe-egusi",
    mealId: "egusi-soup",
    ingredients: [
      { ingredientId: "egusi", ingredientName: "Egusi (Ground Melon Seeds)", quantity: 200, unit: "g" },
      { ingredientId: "beef", ingredientName: "Beef", quantity: 400, unit: "g" },
      { ingredientId: "stockfish", ingredientName: "Stockfish", quantity: 80, unit: "g" },
      { ingredientId: "ugu-leaves", ingredientName: "Ugu Leaves", quantity: 200, unit: "g" },
      { ingredientId: "palm-oil", ingredientName: "Palm Oil", quantity: 120, unit: "ml" },
      { ingredientId: "crayfish", ingredientName: "Ground Crayfish", quantity: 40, unit: "g" },
      { ingredientId: "pepper", ingredientName: "Scotch Bonnet Pepper", quantity: 3, unit: "pieces" },
      { ingredientId: "onion", ingredientName: "Onion", quantity: 1, unit: "piece" },
      { ingredientId: "seasoning-cubes", ingredientName: "Seasoning Cubes", quantity: 2, unit: "cubes" },
      { ingredientId: "salt", ingredientName: "Salt", quantity: "to taste", unit: "" },
    ],
    preparationSteps: [
      "Cook the beef and stockfish with onion, seasoning cubes and salt until tender. Reserve the stock.",
      "Mix the ground egusi with a small amount of water to form a thick paste.",
      "Blend the pepper and set aside. Wash and chop the ugu leaves.",
    ],
    cookingSteps: [
      { id: "cs-e1", mealId: "egusi-soup", stepNumber: 1, title: "Fry the Egusi Paste", instruction: "Heat palm oil in a pot. Drop spoonfuls of the egusi paste into the oil carefully. Fry for 5 minutes without stirring, then gently turn. Let the egusi fry until golden and slightly dry.", duration: 8 },
      { id: "cs-e2", mealId: "egusi-soup", stepNumber: 2, title: "Add Stock & Protein", instruction: "Add the blended pepper and meat stock to the pot. Add the cooked beef and stockfish. Stir carefully to avoid completely breaking the egusi lumps. Cook for 15 minutes on medium heat.", duration: 15 },
      { id: "cs-e3", mealId: "egusi-soup", stepNumber: 3, title: "Add Crayfish & Season", instruction: "Add the ground crayfish and remaining seasoning cubes. Taste and adjust salt. Cook for 5 more minutes allowing flavors to meld.", duration: 5 },
      { id: "cs-e4", mealId: "egusi-soup", stepNumber: 4, title: "Add Vegetables & Serve", instruction: "Add the chopped ugu leaves and stir. Cook for just 2–3 minutes — do not overcook the greens. Remove from heat and serve with pounded yam or eba.", duration: 3 },
    ],
  },
];

export const USERS: User[] = [
  { id: "u1", firstName: "Emem", lastName: "Akpan", email: "emem.akpan@email.com", phone: "08012345678", role: "user", status: "active", joinedAt: "2024-01-15" },
  { id: "u2", firstName: "Uduak", lastName: "Effiong", email: "uduak.effiong@email.com", phone: "08023456789", role: "user", status: "active", joinedAt: "2024-01-20" },
  { id: "u3", firstName: "Nsikak", lastName: "Obot", email: "nsikak.obot@email.com", phone: "08034567890", role: "user", status: "active", joinedAt: "2024-01-25" },
  { id: "u4", firstName: "Asuquo", lastName: "Udo", email: "asuquo.udo@email.com", phone: "08045678901", role: "user", status: "active", joinedAt: "2024-02-01" },
  { id: "u5", firstName: "Iniobong", lastName: "Bassey", email: "iniobong.bassey@email.com", phone: "08056789012", role: "user", status: "suspended", joinedAt: "2024-02-05" },
  { id: "u6", firstName: "Mfon", lastName: "Udoh", email: "mfon.udoh@email.com", phone: "08067890123", role: "user", status: "active", joinedAt: "2024-02-10" },
  { id: "u7", firstName: "Etido", lastName: "Umoren", email: "etido.umoren@email.com", phone: "08078901234", role: "user", status: "active", joinedAt: "2024-02-14" },
  { id: "u8", firstName: "Kufre", lastName: "Essien", email: "kufre.essien@email.com", phone: "08089012345", role: "user", status: "active", joinedAt: "2024-02-18" },
  { id: "u9", firstName: "Ima", lastName: "Ekanem", email: "ima.ekanem@email.com", phone: "08090123456", role: "user", status: "active", joinedAt: "2024-02-22" },
  { id: "u10", firstName: "Obinna", lastName: "Nwosu", email: "obinna.nwosu@email.com", phone: "08001234567", role: "user", status: "active", joinedAt: "2024-03-01" },
  { id: "admin1", firstName: "System", lastName: "Administrator", email: "admin@menudirectorate.ng", phone: "08011111111", role: "admin", status: "active", joinedAt: "2024-01-01" },
];

export const DEFAULT_MEAL_PLAN: MealPlanEntry[] = [
  { id: "mp1", userId: "guest", day: "Monday", mealType: "Breakfast", mealId: "akara" },
  { id: "mp2", userId: "guest", day: "Monday", mealType: "Lunch", mealId: "jollof-rice" },
  { id: "mp3", userId: "guest", day: "Monday", mealType: "Dinner", mealId: "afang-soup" },
  { id: "mp4", userId: "guest", day: "Tuesday", mealType: "Breakfast", mealId: "moi-moi" },
  { id: "mp5", userId: "guest", day: "Tuesday", mealType: "Lunch", mealId: "fried-rice" },
  { id: "mp6", userId: "guest", day: "Tuesday", mealType: "Dinner", mealId: "edikang-ikong" },
  { id: "mp7", userId: "guest", day: "Wednesday", mealType: "Breakfast", mealId: "bread-egg" },
  { id: "mp8", userId: "guest", day: "Wednesday", mealType: "Lunch", mealId: "native-rice" },
  { id: "mp9", userId: "guest", day: "Wednesday", mealType: "Dinner", mealId: "egusi-soup" },
  { id: "mp10", userId: "guest", day: "Thursday", mealType: "Breakfast", mealId: "pap-akamu" },
  { id: "mp11", userId: "guest", day: "Thursday", mealType: "Lunch", mealId: "white-rice-stew" },
  { id: "mp12", userId: "guest", day: "Thursday", mealType: "Dinner", mealId: "okro-soup" },
  { id: "mp13", userId: "guest", day: "Friday", mealType: "Breakfast", mealId: "moi-moi" },
  { id: "mp14", userId: "guest", day: "Friday", mealType: "Lunch", mealId: "jollof-rice" },
  { id: "mp15", userId: "guest", day: "Friday", mealType: "Dinner", mealId: "pepper-soup" },
  { id: "mp16", userId: "guest", day: "Saturday", mealType: "Breakfast", mealId: "akara" },
  { id: "mp17", userId: "guest", day: "Saturday", mealType: "Lunch", mealId: "fried-rice" },
  { id: "mp18", userId: "guest", day: "Saturday", mealType: "Dinner", mealId: "afang-soup" },
  { id: "mp19", userId: "guest", day: "Sunday", mealType: "Breakfast", mealId: "bread-egg" },
  { id: "mp20", userId: "guest", day: "Sunday", mealType: "Lunch", mealId: "pounded-yam" },
  { id: "mp21", userId: "guest", day: "Sunday", mealType: "Dinner", mealId: "edikang-ikong" },
];

export const REPORTS: Report[] = [
  { id: "r1", mealId: "afang-soup", mealName: "Afang Soup", reason: "Incorrect ingredient", description: "The quantity of Afang leaves listed seems too low for 4 servings.", status: "pending", date: "2024-03-10", reportedBy: "Emem Akpan" },
  { id: "r2", mealId: "jollof-rice", mealName: "Jollof Rice", reason: "Incorrect cooking instruction", description: "Step 3 says to add rice before frying the tomato base, which is wrong.", status: "resolved", date: "2024-03-08", reportedBy: "Uduak Effiong" },
  { id: "r3", mealId: "egusi-soup", mealName: "Egusi Soup", reason: "Incorrect quantity", description: "200g of egusi seems too much for the described 4 servings.", status: "dismissed", date: "2024-03-05", reportedBy: "Nsikak Obot" },
  { id: "r4", mealId: "ekpang-nkukwo", mealName: "Ekpang Nkukwo", reason: "Incorrect recipe", description: "The preparation steps do not mention soaking the cocoyam before grating.", status: "pending", date: "2024-03-12", reportedBy: "Kufre Essien" },
  { id: "r5", mealId: "pepper-soup", mealName: "Pepper Soup", reason: "Other", description: "Prep time listed as 10 minutes seems too optimistic when cleaning the fish.", status: "pending", date: "2024-03-14", reportedBy: "Ima Ekanem" },
];

export const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
export const MEAL_TYPES: ("Breakfast" | "Lunch" | "Dinner")[] = ["Breakfast", "Lunch", "Dinner"];
